apiVersion: v1
kind: Service
metadata:
  name: {{ include "commanderscp.fullname" . }}-api
  labels:
    {{- include "commanderscp.apiSelectorLabels" . | nindent 4 }}
    {{- include "commanderscp.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "commanderscp.apiSelectorLabels" . | nindent 4 }}
