import type { InfraKind } from "@scp/schemas";
import { isInfraProductConstruct, type InfraProductScope } from "./infra.js";

/** D20's products module. See docs/iac.md §300. */

const INFRA_KIND_INTERFACE_NAME = {
  cluster: "ICluster",
  instanceGroup: "IInstanceGroup",
  database: "IDatabase",
  bucket: "IBucket",
  queue: "IQueue"
} as const satisfies Record<InfraKind, string>;

/** One entry of a products module — one owned infra product, resolved to what the generated source
 *  needs to print it: a valid JS property name, its interface type name, and its real (not
 *  placeholder) URN + kind. */
export interface ProductEntry {
  /** camelCase JS property name derived from the construct's own id (`pay-blue` -> `payBlue`). */
  readonly identifier: string;
  readonly kind: InfraKind;
  /** The `I<Kind>` interface name this entry's value is typed as (D24). */
  readonly interfaceName: string;
  readonly urn: string;
}

/** camelCase JS identifier from any construct id/slug. See docs/iac.md §301. */
export function camelIdentifier(input: string): string {
  const parts = input
    .trim()
    .split(/[^a-zA-Z0-9]+/)
    .filter((p) => p.length > 0);
  if (parts.length === 0) return "product";
  return parts
    .map((part, i) => {
      const lower = part.toLowerCase();
      return i === 0 ? lower : lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join("");
}

/** Every infra product owned anywhere under `scope`. See docs/iac.md §302. */
export function collectProducts(scope: InfraProductScope): ProductEntry[] {
  const owned = scope.stack._resourcesWithin(scope).filter(isInfraProductConstruct);
  const sorted = [...owned].sort((a, b) => a.urn.localeCompare(b.urn));

  const entries: ProductEntry[] = [];
  const byIdentifier = new Map<string, ProductEntry>();
  for (const resource of sorted) {
    const identifier = camelIdentifier(resource.id);
    const existing = byIdentifier.get(identifier);
    if (existing) {
      throw new Error(
        `Products module for "${scope.path}": both "${existing.urn}" and "${resource.urn}" map to ` +
          `the identifier "${identifier}" — rename one of the two construct ids so the generated ` +
          `module does not silently drop one of them.` +
          // When two urns print the same, the collision is upstream. See docs/iac.md §303.
          (existing.urn === resource.urn
            ? ` Both URNs are identical, which means the construct ids differ only in case or ` +
              `punctuation — they are two constructs sharing one object identity, and Stack.synth() ` +
              `refuses that manifest for the same reason.`
            : "")
      );
    }
    const entry: ProductEntry = {
      identifier,
      kind: resource.kind,
      interfaceName: INFRA_KIND_INTERFACE_NAME[resource.kind],
      urn: resource.urn
    };
    byIdentifier.set(identifier, entry);
    entries.push(entry);
  }
  return entries;
}

/** Renders `entries` as the module's TypeScript SOURCE TEXT. See docs/iac.md §304. */
export function renderProductsModule(entries: readonly ProductEntry[]): string {
  const header =
    "// GENERATED by `@scp/iac` synth (team-pipeline-iac.md D20) — DO NOT EDIT BY HAND.\n" +
    "// Regenerate by re-running this pipeline's synth step. The wire manifest carries only URNs;\n" +
    "// this module exists purely so a consuming repo gets a compile-time-checked `placeAt(...)`.\n";

  if (entries.length === 0) {
    return `${header}\nexport const products = {} as const;\n`;
  }

  const usedInterfaces = [...new Set(entries.map((e) => e.interfaceName))].sort((a, b) =>
    a.localeCompare(b)
  );
  const importLine = `import type { ${usedInterfaces.join(", ")} } from "@scp/iac";\n\n`;

  const typeLines = entries
    .map((e) => `  readonly ${e.identifier}: ${e.interfaceName};`)
    .join("\n");
  const valueLines = entries
    .map(
      (e) =>
        `  ${e.identifier}: { urn: ${JSON.stringify(e.urn)}, typeId: "deployment-target", kind: ${JSON.stringify(e.kind)} }`
    )
    .join(",\n");

  return (
    `${header}${importLine}` + `export const products: {\n${typeLines}\n} = {\n${valueLines}\n};\n`
  );
}

/** `collectProducts(scope)` piped straight into `renderProductsModule` — the one call an infra
 *  pipeline's own synth step reaches for (`pipeline.ts`'s `PipelineBase.synthProducts()`). */
export function productsModuleSource(scope: InfraProductScope): string {
  return renderProductsModule(collectProducts(scope));
}
