import type {
  DesiredStateManifest,
  ExecutorType,
  ManifestObject,
  ManifestPipelineHook
} from "@scp/schemas";

/**
 * D21(d): `scp iac render` regenerates the human-readable pipeline picture from a SYNTHESIZED
 * manifest — pure string transforms, exactly like `Stack.synth()`/`products.ts` are pure; the CLI
 * (`packages/cli/src/cli.ts`) owns the only I/O (reading `--manifest`, writing `--write`).
 *
 * ============================================================================================
 * THE HARD PART, AND THE REASON THIS EXISTS: D21(d)'S "ALL GATES", HONESTLY
 * ============================================================================================
 * "`scp iac render` shows ALL gates that will apply, including estate-imposed ones the team never
 * declared (the scan gate at the registry) — the picture must be the truth, not the team's subset
 * of it." This module runs OFFLINE against a manifest file alone (D21(d)'s own constraint — render
 * is a local dev-loop tool, not an API call), so it genuinely cannot see domain binding policy, an
 * org's scan requirements, or anything else that lives server-side. Two things follow, and both are
 * load-bearing:
 *
 *   1. The FIXED estate-imposed gates the canonical journey (D21/D22) always applies — the registry
 *      scan + origin signature, the commander's per-crossing signature, the build's own unit gate —
 *      are DOCUMENTED FACTS about how this platform's build/promotion path works, not something a
 *      manifest could ever carry (D22's build order runs entirely inside the team's own build
 *      workflow, before SCP ever sees the artifact). Render states them explicitly, every time, for
 *      every build-family pipeline, so the picture is never just "what this team happened to type".
 *   2. Beyond that fixed set, render CANNOT know what a domain's binding policy or an org's own
 *      additional scan/security rules require — that is real information this view does not have.
 *      `MANIFEST_ONLY_DISCLAIMER` says so, in the output, every time — an honest boundary line
 *      rather than a picture that LOOKS complete and silently isn't (D21(d)'s literal test).
 */

const BUILD_FAMILY: ReadonlySet<ExecutorType> = new Set([
  "image",
  "chart",
  "rpm",
  "deb",
  "vm-image",
  "npm",
  "maven",
  "python",
  "go"
]);

/** Kinds `PLACEMENT_MATRIX` (`infra.ts`) ever gives a non-empty row — i.e. kinds that cross a CDS
 *  boundary on their way to a real deploy target, as opposed to publish-only artifacts. Duplicated
 *  as a literal (not imported from `infra.ts`) on purpose: `render.ts` only needs the KIND names,
 *  not the compatibility matrix itself, and importing `infra.ts` here would pull `@scp/schemas`'s
 *  `InfraKind` type into a module whose whole job is staying a thin, manifest-only reader. */
const PLACED_KINDS: ReadonlySet<ExecutorType> = new Set([
  "image",
  "chart",
  "rpm",
  "deb",
  "vm-image",
  "configuration"
]);

export const MANIFEST_ONLY_DISCLAIMER =
  "NOTE: this view is manifest-only (D21(d)). Gates shown above are (a) exactly what THIS " +
  "manifest declares — waves, placements, pipelineHooks — and (b) the FIXED set of estate-imposed " +
  "gates the canonical journey (D21/D22) always applies, spelled out explicitly per pipeline above. " +
  "It cannot see domain-specific binding-policy gates or any other org rule beyond that fixed set — " +
  "estate-imposed gates are not shown beyond what is listed here.";

export const RENDER_BEGIN_MARKER =
  "/* ─── GENERATED by `scp iac render --write` (team-pipeline-iac.md D21(d)) — DO NOT EDIT BELOW ───";
export const RENDER_END_MARKER =
  " * ─── END GENERATED — regenerate with `scp iac render --write` ─── */";

export interface RenderedPipeline {
  readonly componentUrn: string;
  readonly name: string;
  readonly kind: ExecutorType;
  /** Body lines, no comment prefix — `formatPipelineBlock` adds the ` * ` prefix and the header/
   *  footer rule when embedding this into the generated comment block. */
  readonly lines: string[];
}

function objectByUrn(manifest: DesiredStateManifest, urn: string): ManifestObject | undefined {
  return manifest.objects.find((o) => o.urn === urn);
}

/** A human name for a wave target URN — the real object's `name` when it is in this manifest's own
 *  `objects` (an infra product/stage this stack also declares), else the URN's last path segment
 *  (a `fromName()`/`fromUrn()` reference to something declared elsewhere — the common case for a
 *  stage name). Never throws: an unresolvable reference still renders as SOMETHING readable. */
function targetLabel(manifest: DesiredStateManifest, urn: string): string {
  const obj = objectByUrn(manifest, urn);
  if (obj) return obj.name;
  const parts = urn.split(":");
  return parts[parts.length - 1] ?? urn;
}

function hookLine(hook: ManifestPipelineHook): string {
  switch (hook.kind) {
    case "postMerge":
      return (
        `postMerge   ${hook.hookId}   ${hook.workflow.path} @ ${hook.workflow.repo}:${hook.workflow.branch}` +
        " — gates entry to wave 1"
      );
    case "postDeploy":
      return `postDeploy  ${hook.hookId}   stage: ${hook.stage ?? "ALL waves (default, D21(a))"}`;
    case "continuous":
      return (
        `continuous  ${hook.hookId}   every ${hook.everySeconds}s, maxAge ${hook.maxAgeSeconds}s` +
        " — per-target hold"
      );
    case "bakeAlarms":
      return (
        `bakeAlarms  ${hook.hookId}   quiet ${hook.quietWindowSeconds}s, ` +
        `stage: ${hook.stage ?? "ALL waves (default)"}`
      );
  }
}

/** The FIXED, always-true estate-imposed gates D21/D22 name for the canonical journey — never read
 *  from the manifest (see this module's doc for why they cannot be). */
function estateImposedGateLines(kind: ExecutorType): string[] {
  if (kind === "infrastructure") {
    return [
      "  (an Infrastructure pipeline produces products; it is never itself placed — D24 — so it " +
        "has no build/registry/CDS gates of its own)"
    ];
  }
  if (kind === "configuration") {
    return [
      "  - digest-bound scan + origin signature at the registry, gating push (D22 build order: " +
        "build -> unit -> scan -> origin signature -> push)",
      "  - the commander's crossing signature, gating each CDS crossing a wave's targets cross " +
        "into a new security domain (D21(c)/D22)",
      "  - D25 convergence may re-apply already-released, already-gated state when this pipeline's " +
        "placed infra product's membership changes — not a new release, no wave re-entry"
    ];
  }
  const lines = [
    "  - build succeeds + unit tests pass (D22 build order) — the build's own internal gate, " +
      "DISPLAYED here per D21(d) even though SCP gates entry to wave 1, not the build itself " +
      "(owner ruling 2026-08-26)",
    "  - digest-bound scan + origin signature at the registry, gating push (D22 build order: " +
      "build -> unit -> scan -> origin signature -> push)"
  ];
  if (PLACED_KINDS.has(kind)) {
    lines.push(
      "  - the commander's crossing signature, gating each CDS crossing a wave's targets cross " +
        "into a new security domain (D21(c)/D22); staging spans every security domain before any " +
        "production wave (D21(c))"
    );
  }
  return lines;
}

/**
 * Renders ONE pipeline's picture, pure — the body of the generated block. `componentUrn`/`kind`
 * identify which `releases_via` relationship this is for (a manifest may declare several pipelines,
 * one per `releases_via` edge — image + infrastructure sharing a repo is the worked example's own
 * shape); the topology object it points to carries the waves.
 */
export function renderPipelineLines(
  manifest: DesiredStateManifest,
  componentUrn: string,
  kind: ExecutorType,
  topologyUrn: string
): string[] {
  const lines: string[] = [];
  const component = objectByUrn(manifest, componentUrn);
  const topology = objectByUrn(manifest, topologyUrn);
  const waves = ((topology?.properties?.["waves"] as unknown[] | undefined) ?? []) as Array<{
    name?: string;
    mode: "parallel" | "sequential";
    targets: string[];
  }>;

  const sourceMapping = (manifest.sourceMappings ?? []).find(
    (m) => m.componentUrn === componentUrn && (m.type ?? "configuration") === kind
  );
  if (sourceMapping) {
    const ref = sourceMapping.refPattern
      ? ` @ ${sourceMapping.refPattern.replace(/^refs\/heads\//, "")}`
      : "";
    const path = sourceMapping.pathPattern ? ` (path: ${sourceMapping.pathPattern})` : "";
    lines.push(`source     ${sourceMapping.repoPattern ?? "*"}${ref}${path}`);
  } else {
    lines.push("source     (no source mapping declared in this manifest for this pipeline)");
  }

  if (BUILD_FAMILY.has(kind)) {
    const publishesTo = manifest.relationships.find(
      (r) => r.typeId === "publishes_to" && r.fromUrn === componentUrn
    );
    if (publishesTo) {
      const repository = (publishesTo.properties?.["repository"] as string | undefined) ?? "";
      lines.push(`publish    ${targetLabel(manifest, publishesTo.toUrn)}/${repository}`);
    }
  }

  lines.push("");
  lines.push("waves:");
  waves.forEach((wave, i) => {
    const label = wave.name ?? `wave${i + 1}`;
    const targets = wave.targets.map((t) => targetLabel(manifest, t)).join(", ");
    lines.push(`  ${label}   ${wave.mode}   ${targets}`);
  });

  lines.push("");
  const hooks = (manifest.pipelineHooks ?? []).filter((h) => h.componentUrn === componentUrn);
  if (hooks.length > 0) {
    lines.push("declared hooks (from this manifest, D11/D21):");
    for (const hook of hooks) lines.push(`  ${hookLine(hook)}`);
  } else {
    lines.push("declared hooks: (none declared in this manifest)");
  }

  lines.push("");
  lines.push("estate-imposed gates (D21/D22 — NOT declared in this manifest, always apply):");
  lines.push(...estateImposedGateLines(kind));

  return [`pipeline   ${component?.name ?? componentUrn} (${kind})`, "", ...lines];
}

/** Every `releases_via` edge in `manifest` (D8/D17: one per declared pipeline), rendered. Sorted by
 *  `(componentUrn, kind)` so declaration order never changes which block comes first. */
export function renderManifestPipelines(manifest: DesiredStateManifest): RenderedPipeline[] {
  const releasesVia = manifest.relationships.filter((r) => r.typeId === "releases_via");
  const sorted = [...releasesVia].sort((a, b) => {
    const aKind = String(a.properties?.["type"] ?? "");
    const bKind = String(b.properties?.["type"] ?? "");
    return `${a.fromUrn} ${aKind}`.localeCompare(`${b.fromUrn} ${bKind}`);
  });

  return sorted.map((rel) => {
    const kind = (rel.properties?.["type"] as ExecutorType | undefined) ?? "configuration";
    const component = objectByUrn(manifest, rel.fromUrn);
    return {
      componentUrn: rel.fromUrn,
      name: component?.name ?? rel.fromUrn,
      kind,
      lines: renderPipelineLines(manifest, rel.fromUrn, kind, rel.toUrn)
    };
  });
}

/** Wraps one `RenderedPipeline`'s lines in the comment-block delimiters the worked examples show
 *  (team-pipeline-iac-examples.md §7's `payments-api` block), so the block reads identically inside
 *  a committed `.ts` file and on stdout. */
export function formatPipelineBlock(pipeline: RenderedPipeline): string {
  const rule = " * " + "─".repeat(75);
  const body = pipeline.lines.map((l) => (l.length > 0 ? ` * ${l}` : " *")).join("\n");
  return [
    `/* ${"─".repeat(2)} pipeline: ${pipeline.name} (${pipeline.kind}) ${"─".repeat(2)}`,
    body,
    rule,
    " */"
  ].join("\n");
}

/**
 * The full generated section — every pipeline's block, the honesty disclaimer, wrapped once in the
 * BEGIN/END markers `updateGeneratedSection` looks for. This is what `--write` inserts and what
 * plain `scp iac render` prints to stdout, so the two are always byte-identical modulo where they
 * land (drift-check: running `--write` twice on an unchanged manifest is a no-op diff).
 */
export function renderManifestSection(manifest: DesiredStateManifest): string {
  const pipelines = renderManifestPipelines(manifest);
  const blocks =
    pipelines.length > 0
      ? pipelines.map((p) => formatPipelineBlock(p)).join("\n\n")
      : "(no pipelines — no `releases_via` relationship in this manifest)";
  return [
    RENDER_BEGIN_MARKER,
    "",
    blocks,
    "",
    ` * ${MANIFEST_ONLY_DISCLAIMER}`,
    "",
    RENDER_END_MARKER
  ].join("\n");
}

/**
 * `--write`'s pure string surgery: replaces the marked generated section in `existingSource` with
 * `generatedSection`, or APPENDS it (with a blank-line separator) when no marker is present yet —
 * the first run against a hand-authored file. Idempotent: calling this twice in a row with the same
 * `generatedSection` on its own output is a no-op, which is what makes `scp iac render --write` a
 * meaningful CI drift check (regenerate, then `git diff --exit-code`).
 */
export function updateGeneratedSection(existingSource: string, generatedSection: string): string {
  const beginIndex = existingSource.indexOf(RENDER_BEGIN_MARKER);
  if (beginIndex === -1) {
    const trimmed = existingSource.replace(/\s+$/, "");
    const separator = trimmed.length > 0 ? "\n\n" : "";
    return `${trimmed}${separator}${generatedSection}\n`;
  }
  const prefix = existingSource.slice(0, beginIndex).replace(/\s+$/, "");
  const separator = prefix.length > 0 ? "\n\n" : "";
  return `${prefix}${separator}${generatedSection}\n`;
}
