import { defineConfig } from "@hey-api/openapi-ts";

/**
 * Generates the SDK core from the committed OpenAPI 3.1 spec (BUILD_AND_TEST.md §3.2).
 * `@hey-api/client-fetch` is a required runtime dependency of the generated client code —
 * `@hey-api/openapi-ts` has no client-less mode — everything else here mirrors DESIGN.md §15.
 *
 * ADR-0023 — RESPONSE VALIDATION. The `zod` plugin emits a runtime schema per operation RESPONSE
 * and `validator: { response: "zod" }` attaches it to that operation as `responseValidator`, which
 * the generated client awaits on the 2xx JSON path. This is what stops a required-but-absent field
 * (version skew between a client and an instance) from surfacing as a bare `TypeError` deep inside
 * a component; `src/response-validation.ts` turns the rejection into one diagnosable error naming
 * the operation and the field. `requests`/`definitions`/`metadata` are off because only responses
 * are validated — emitting request and component schemas would double the generated bytes for
 * nothing. Generation is fully offline: the zod plugin ships inside `@hey-api/openapi-ts` and the
 * input is the committed local spec file (charter principle 5).
 */
export default defineConfig({
  input: "../../tools/openapi/openapi.v1.json",
  output: "src/generated",
  plugins: [
    "@hey-api/client-fetch",
    "@hey-api/typescript",
    { name: "zod", requests: false, definitions: false, metadata: false },
    { name: "@hey-api/sdk", validator: { response: "zod" } }
  ]
});
