/**
 * THE TWO FILES A HOST NEEDS, and nothing else (M27.8, ADR-0051 D4).
 *
 * ADR-0051 D4 accepts a standing host footprint and justifies it rather than engineering it away.
 * This module is that justification made concrete: enrolling a host is **two static files**. No
 * daemon, no scheduled callback, no listener beyond the `sshd` already running, no SCP code
 * resident on the host. The host initiates nothing and, between runs, is doing nothing.
 *
 * Generated rather than documented because a copy-pasted sudoers line is how a fleet ends up with
 * `NOPASSWD:ALL` — and because the command list is derived from the CATALOG, so it cannot drift
 * from what the runner is actually able to invoke.
 */

/** A catalog role's name and the commands it needs, as the catalog declares them. */
export interface EnrolmentCommandSet {
  /** The charter class, for the comment the operator reads above the rule. */
  charterClass: string;
  /** Absolute paths. Relative ones are refused — a relative command in sudoers resolves through
   *  the invoking user's PATH, which is the classic sudoers escape. */
  commands: readonly string[];
}

export class EnrolmentGenerationError extends Error {}

/**
 * `TrustedUserCAKeys` content: the CA public key hosts trust for USER certificates.
 *
 * ONE KEY PER LINE and nothing else. The file is a trust anchor; a stray comment or a second key
 * is a second authority nobody decided to trust.
 */
export function trustedUserCaKeysFile(caPublicKey: string): string {
  const key = caPublicKey.trim();
  if (!key.startsWith("ssh-ed25519 ")) {
    throw new EnrolmentGenerationError(
      "refusing to emit TrustedUserCAKeys: the CA public key is not an ssh-ed25519 key"
    );
  }
  if (key.includes("\n")) {
    throw new EnrolmentGenerationError(
      "refusing to emit TrustedUserCAKeys: the CA public key spans multiple lines, which would " +
        "install more than one trust anchor"
    );
  }
  return `${key}\n`;
}

/**
 * A restricted sudoers fragment — exactly the catalog's commands, NEVER `NOPASSWD:ALL`.
 *
 * The principal is the certificate's, so the rule grants nothing to a human account. Each command
 * must be absolute: a relative command in sudoers is resolved through PATH at invocation time,
 * which turns a restricted rule into an unrestricted one for anyone who can influence PATH.
 */
export function sudoersFragment(
  principal: string,
  sets: Record<string, EnrolmentCommandSet>
): string {
  if (!/^[a-z_][a-z0-9_-]*$/.test(principal)) {
    // A principal is written verbatim into a sudoers rule; anything that could terminate the field
    // would rewrite the rule rather than fill it in.
    throw new EnrolmentGenerationError(
      `refusing to emit sudoers: '${principal}' is not a plain login name`
    );
  }
  const lines: string[] = [
    "# GENERATED BY CommanderSCP — scp-runner-ops enrolment (M27.8, ADR-0051 D4).",
    "#",
    "# Exactly the commands the signed task catalog can invoke, and nothing else. This is the",
    "# second of the two static files host enrolment installs; the first is TrustedUserCAKeys.",
    "# There is no daemon, no callback and no SCP code on this host.",
    "#",
    "# NEVER add NOPASSWD:ALL here. The whole containment argument for host-reaching managed",
    "# execution is that the operations are a bounded, reviewed vocabulary; a wildcard replaces",
    "# that argument with nothing.",
    ""
  ];
  const names = Object.keys(sets).sort();
  if (names.length === 0) {
    throw new EnrolmentGenerationError(
      "refusing to emit an EMPTY sudoers fragment: a file granting nothing reads as though " +
        "enrolment succeeded while every run would fail at the first privileged task"
    );
  }
  for (const name of names) {
    const set = sets[name]!;
    const relative = set.commands.filter((c) => !c.startsWith("/"));
    if (relative.length > 0) {
      throw new EnrolmentGenerationError(
        `refusing to emit sudoers for role '${name}': ${relative.join(", ")} is not an absolute ` +
          "path. A relative command resolves through PATH at invocation, which makes a restricted " +
          "rule unrestricted for anyone who can set it."
      );
    }
    lines.push(`# ${name} (${set.charterClass})`);
    lines.push(`${principal} ALL=(root) NOPASSWD: ${[...set.commands].sort().join(", ")}`);
    lines.push("");
  }
  return lines.join("\n");
}
