/**
 * Python — `pyproject.toml` **and** `requirements.txt`, because a real Python component may declare
 * in either and many declare in both.
 *
 * **"Declared vs pinned differ, record which it was."** This is the ecosystem where that matters
 * most and where it is most often lost. `requests>=2.31` and `requests==2.31.0` are different
 * statements about the same package: the first delegates the choice to the resolver, the second
 * takes it. A `requirements.txt` that is machine-generated by `pip freeze` is wall-to-wall `==`
 * pins, while a hand-written `pyproject.toml` is wall-to-wall ranges — and the SAME component often
 * has both, one being the compiled output of the other. Flattening the two into "a version" would
 * make an actuator rewrite a project's dependency POLICY while believing it bumped a version, so
 * {@link DeclaredDependency.constraint} carries `pinned` vs `range` and
 * {@link DeclaredDependency.declaredIn} carries which file section it came from.
 *
 * Lockfile-adjacent files (`poetry.lock`, `Pipfile.lock`, `*.txt` produced with `--hash`) are not
 * read: ADR-0032 §8 forbids lockfile resolution outright, and §4 forbids storing the closure. A
 * `pip freeze`-style `requirements.txt` IS effectively a closure, but it is what the component
 * *declares* — this package reports the declaration in the file it was handed and does not go
 * looking for a deeper one.
 *
 * Tables read from `pyproject.toml`:
 * - `[project].dependencies`               (PEP 621)  -> runtime
 * - `[project.optional-dependencies].<g>`  (PEP 621)  -> runtime, group in `declaredIn`
 * - `[dependency-groups].<g>`              (PEP 735)  -> dev   (the standard dev-group mechanism)
 * - `[build-system].requires`              (PEP 518)  -> build (genuinely build-scope: needed to
 *                                                       produce the wheel, never shipped in it)
 * - `[tool.poetry.dependencies]`                      -> runtime
 * - `[tool.poetry.group.<g>.dependencies]`            -> dev
 * - `[tool.poetry.dev-dependencies]` (legacy)         -> dev
 *
 * `python = "^3.11"` inside a Poetry dependency table is EXCLUDED: it is the interpreter constraint,
 * not a package. Subscribing a component to "the 3.x line of python" via its dependency inventory
 * would produce a bump commit that changes the supported interpreter range.
 *
 * A PEP 508 environment marker (`; python_version < "3.9"`) does not change *which* package is
 * declared, only whether it installs somewhere. It is stripped from the specifier and does not
 * suppress the dependency — a conditionally-installed package still needs its security bumps.
 */
import { ManifestParseError, type DeclaredDependency, type DependencyScope } from "./types.js";
import { scanToml, tableEntries, type TomlEntry, type TomlValue } from "./toml-lite.js";
import { parseComparableVersion } from "./version.js";

/**
 * PEP 508: `name [extras] specifier ; marker` or `name @ url ; marker`.
 *
 * **The leading `[A-Za-z0-9]` anchor is load-bearing, not cosmetic.** It is the sole mechanism that
 * keeps a `requirements.txt` OPTION line out of the inventory: `--only-binary numpy`,
 * `-r base.txt`, `--index-url …` all begin with `-`, so they cannot match here and
 * {@link parseRequirementsTxt} needs no separate leading-`-` test (there used to be one; it was
 * provably unreachable, and dead code that reads as the enforcement is its own hazard — a later
 * editor loosening this charset would have believed the other line was still holding the door).
 * Anything that widens this character class — PEP 625 name normalisation, say — must re-check
 * `--only-binary numpy`, whose argument is the one option argument that reads as a requirement.
 *
 * The name charset is PEP 508's own (`[A-Za-z0-9]` with `.`, `-`, `_` internally). Extras are
 * captured separately: `celery[redis]` and `celery` are the SAME distribution with different
 * optional features, so the coordinate is `celery` and the extras go in the note. Keeping the
 * extras in the coordinate would split one package into N inventory identities, and the reverse
 * query ADR-0032 §4 relies on ("which components subscribe to P?") would miss them all.
 */
const PEP508_RE = /^([A-Za-z0-9][A-Za-z0-9._-]*)\s*(?:\[([^\]]*)\])?\s*(.*)$/;

/** `==1.2.3` / `===1.2.3` naming exactly one version. `==1.2.*` is a range and is excluded here. */
const PY_EXACT_RE = /^={2,3}\s*[^\s,*]+$/;

/**
 * A `requirements.txt` line whose leading token is a URL SCHEME rather than a distribution name.
 *
 * The rule is "the leading token is immediately followed by `+` or `:`" — decidable without knowing
 * any scheme at all, and correct in all three directions this guard has been wrong in:
 *
 * - **It is a delimiter test, not a prefix test.** A prefix test (`/^(https?|git\+|file:)/i`)
 *   discards every distribution whose NAME merely begins with a scheme word — httpx, httpcore,
 *   httptools, httplib2, httpie, filelock and gitpython are all real PyPI packages, and they
 *   vanished with no row, no note and no error. Silent deletion of a real dependency is the outcome
 *   {@link ManifestParseError} exists to prevent; producing it from a guard is that same failure
 *   inside one parser.
 * - **It covers the whole class, not the one scheme somebody remembered.** pip documents FOUR VCS
 *   schemes: `git+`, `hg+`, `svn+`, `bzr+` (pip docs, "VCS Support"). A version of this guard that
 *   enumerated only `git+` let `hg+https://example/x` fall through to {@link PEP508_RE}, which read
 *   it as a distribution named `hg` — with `svn` and `bzr` behind it. Phantom package names that no
 *   index resolves, attached to a real component.
 * - **A MALFORMED scheme is refused too, deliberately.** `http:example` (no `//`) and
 *   `git+https//broken` (no scheme colon) are neither URLs nor valid PEP 508: the name charset is
 *   `[A-Za-z0-9._-]` and no specifier operator begins with `+` or `:`, so nothing valid can look
 *   like this. Demanding a WELL-FORMED URL here would send exactly those two on to
 *   {@link PEP508_RE} and mint the coordinates `http` and `git` — a distribution named after the
 *   scheme of the URL somebody meant to type. Refusing matches `dockerfile.ts:209-214`, which skips
 *   `FROM :1.0` rather than minting an empty-name coordinate: a dependency carrying a WRONG identity
 *   is worse than one that is missing, because the missing one is visibly missing.
 *
 * Enumerating schemes on top of this would buy nothing and cost something. The verdict for a
 * well-formed and for a malformed VCS URL is identical — no row — so a scheme-listing regex ahead of
 * this one could never change an outcome, i.e. it would be the dead-guard-that-reads-as-the-
 * enforcement hazard described on {@link PEP508_RE}. The scheme list belongs in this comment and in
 * the tests, where it is a statement about the world, not a branch that can quietly stop mattering.
 *
 * Refusal is per-LINE, never a {@link ManifestParseError}: one mistyped URL does not mean the file
 * is not a requirements.txt, and throwing would delete the inventory of every correctly-spelled line
 * beside it.
 */
const SCHEME_LINE_RE = /^[A-Za-z0-9][A-Za-z0-9._-]*[+:]/;

interface ParsedRequirement {
  readonly coordinate: string;
  readonly declared?: string;
  readonly constraint: DeclaredDependency["constraint"];
  readonly note?: string;
}

/**
 * Parse one PEP 508 requirement string into a coordinate plus a classified constraint.
 *
 * Returns `undefined` for a string that names no distribution at all (a bare URL, an empty line) —
 * there is nothing to subscribe to, and inventing a coordinate from a URL's path would be exactly
 * the "inferred from a name" mistake ADR-0030 §2 warns about.
 */
export function parsePep508(requirement: string): ParsedRequirement | undefined {
  // Strip the environment marker: it gates installation, not identity.
  const semicolon = requirement.indexOf(";");
  const withoutMarker = (semicolon === -1 ? requirement : requirement.slice(0, semicolon)).trim();
  if (withoutMarker === "") return undefined;

  const m = PEP508_RE.exec(withoutMarker);
  const name = m?.[1];
  if (!m || name === undefined) return undefined;

  const extras = m[2];
  const rest = (m[3] ?? "").trim();
  const extrasNote =
    extras !== undefined && extras.trim() !== ""
      ? `extras [${extras.trim()}] declared; extras select optional features of the same distribution and do not change its identity`
      : undefined;

  // Direct reference (PEP 440 §"Direct references"): `pkg @ https://…/pkg-1.0.whl`. The version is
  // baked into a URL and is not a registry line; unresolved, never parsed out of the path.
  if (rest.startsWith("@")) {
    return {
      coordinate: name,
      declared: rest,
      constraint: "unresolved",
      note: "direct-reference URL specifier: not a registry version line"
    };
  }

  // Parenthesised specifier form: `name (>=1.0)`.
  const spec = rest.startsWith("(") && rest.endsWith(")") ? rest.slice(1, -1).trim() : rest;

  if (spec === "") {
    return {
      coordinate: name,
      constraint: "unpinned",
      ...(extrasNote !== undefined ? { note: extrasNote } : {})
    };
  }

  return {
    coordinate: name,
    declared: spec,
    constraint: PY_EXACT_RE.test(spec) ? "pinned" : "range",
    ...(extrasNote !== undefined ? { note: extrasNote } : {})
  };
}

/**
 * One clause of a comma-separated specifier: an optional operator, then the version text.
 *
 * Longest-first alternation so `>=` is never read as `>` and `~=` never as `~`. Poetry's own `^`/`~`
 * are in the same set because {@link comparableFrom} is shared by both the PEP 508 path and the
 * Poetry path below — Poetry writes `^2.32.3` where PEP 508 writes `>=2.32.3,<3`.
 */
const PY_CLAUSE_RE = /^(===|==|~=|!=|>=|<=|\^|~|>|<)?\s*(.*)$/;

/**
 * Operators whose clause names the FLOOR of the declared line — the version the component is at or
 * above today. Everything absent from this set (`!=`, `<`, `<=`) names something the component is
 * explicitly NOT at, and recording it as {@link DeclaredDependency.version} inverts the field's
 * meaning: `sqlalchemy!=1.4.0,>=1.3` would record 1.4.0, the one version the manifest FORBIDS, and
 * `urllib3<3,>=1.21.1` would record 3.0.0, a ceiling the component may never install. A detection
 * tick reading either sees a component "already at" a version it is nowhere near and reports no
 * upgrade.
 *
 * This is not an exotic spelling. `packaging.SpecifierSet.__str__` sorts its clauses, and both `!`
 * (0x21) and `<` (0x3C) sort before `>` (0x3E), so exclusion-first and ceiling-first is exactly what
 * a pip-compile or PKG-INFO round-trip emits — the first clause is routinely NOT the floor.
 *
 * `>` is included: `>2.0` excludes the endpoint but still names where the line starts, whereas `!=`
 * punches a hole in an otherwise unbounded range and `<`/`<=` say nothing about the floor at all.
 * The empty operator is included for Poetry's bare `2.0.32`, which names exactly one version.
 *
 * Where NO clause denotes a floor, the answer is `undefined` — ADR-0032 §7's "skipped rather than
 * guessed" applied to specifiers, and {@link DeclaredDependency.version}'s documented first-class
 * outcome. A missed bump costs a tick; a guessed one costs a wrong commit in someone's repo.
 */
const PY_FLOOR_OPS: ReadonlySet<string> = new Set(["", "===", "==", "~=", ">=", ">", "^", "~"]);

/** The floor clause of a specifier, or `undefined` when no clause states one. */
function comparableFrom(spec: string | undefined): ReturnType<typeof parseComparableVersion> {
  if (spec === undefined) return undefined;
  for (const raw of spec.split(",")) {
    const clause = raw.trim();
    if (clause === "") continue;
    const m = PY_CLAUSE_RE.exec(clause);
    if (!m) continue;
    if (!PY_FLOOR_OPS.has(m[1] ?? "")) continue;
    const parsed = parseComparableVersion((m[2] ?? "").trim());
    if (parsed !== undefined) return parsed;
  }
  return undefined;
}

function toDeclared(
  parsed: ParsedRequirement,
  scope: DependencyScope,
  declaredIn: string,
  line?: number
): DeclaredDependency {
  const version = parsed.constraint === "unresolved" ? undefined : comparableFrom(parsed.declared);
  return {
    ecosystem: "python",
    coordinate: parsed.coordinate,
    ...(parsed.declared !== undefined ? { declared: parsed.declared } : {}),
    constraint: parsed.constraint,
    scope,
    ...(version !== undefined ? { version } : {}),
    declaredIn,
    ...(line !== undefined ? { line } : {}),
    ...(parsed.note !== undefined ? { note: parsed.note } : {})
  };
}

// -------------------------------------------------------------------------------------------------
// requirements.txt
// -------------------------------------------------------------------------------------------------

/**
 * Parse a `requirements.txt`.
 *
 * Option lines are skipped rather than parsed (by {@link PEP508_RE}'s anchor — see there): `-r
 * base.txt` and `-c constraints.txt` point at ANOTHER FILE, and following them would be this package
 * doing I/O, which it never does — the caller that fetched this file is the only thing that can
 * fetch a second one. `-e .` is an editable install of the component itself, not a dependency of it.
 *
 * Never throws. Unlike the other four parsers (see the entry point's contract note), a
 * `requirements.txt` has no required construct whose absence proves the file is not one, so there is
 * nothing to distinguish "empty" from "unreadable" on.
 *
 * `--hash=sha256:…` fragments appended to a requirement are stripped: they pin bytes for an already
 * pinned version and add nothing to the coordinate.
 */
export function parseRequirementsTxt(content: string): DeclaredDependency[] {
  const out: DeclaredDependency[] = [];
  const physical = content.split(/\r?\n/);

  let buffer = "";
  let startLine = 0;

  const flush = (): void => {
    const text = buffer.trim();
    buffer = "";
    if (text === "") return;

    // Option lines (`-r base.txt`, `-e .`, `--index-url …`, `--only-binary numpy`) are NOT filtered
    // here. PEP508_RE's leading `[A-Za-z0-9]` anchor already excludes every line beginning with `-`,
    // so the guard that used to sit on this line could not fire for any input — and a redundant
    // guard that reads as the enforcement is worse than none, because the next person to widen the
    // name charset checks the guard, sees it, and never looks at the anchor. The invariant now lives
    // on PEP508_RE itself, where it is actually enforced. `parseRequirementsTxt` option-line
    // behaviour stays pinned by its own tests below.

    // A URL, VCS or path requirement names no distribution we can key on — whether it is spelled
    // correctly or not. One guard covers both, for the reasons on SCHEME_LINE_RE.
    if (SCHEME_LINE_RE.test(text) || text.startsWith(".") || text.startsWith("/")) return;

    const withoutHashes = text.replace(/\s--hash=\S+/g, "").trim();
    const parsed = parsePep508(withoutHashes);
    if (!parsed) return;
    // requirements.txt expresses no scope distinction whatsoever — the convention of a separate
    // `requirements-dev.txt` is a FILENAME convention, and inferring scope from a filename is the
    // provenance-label mistake (a label named after what matched goes false the moment a second
    // kind of file matches). The caller knows which file it fetched; this parser does not guess.
    out.push(toDeclared(parsed, "runtime", "requirements.txt", startLine));
  };

  for (let i = 0; i < physical.length; i++) {
    const raw = physical[i] ?? "";
    // A `#` comment runs to end of line. `#` cannot appear inside a requirement specifier.
    const hash = raw.indexOf("#");
    const code = (hash === -1 ? raw : raw.slice(0, hash)).trimEnd();
    if (code.trim() === "" && buffer === "") continue;

    if (buffer === "") startLine = i + 1;

    if (code.endsWith("\\")) {
      buffer += `${code.slice(0, -1).trim()} `;
      continue;
    }
    buffer += code;
    flush();
  }
  flush();

  return out;
}

// -------------------------------------------------------------------------------------------------
// pyproject.toml
// -------------------------------------------------------------------------------------------------

/** Pull the string items out of an array value, ignoring anything that is not a string. */
function stringItems(value: TomlValue): string[] {
  if (value.kind !== "array") return [];
  return value.items.flatMap((item) => (item.kind === "string" ? [item.value] : []));
}

/**
 * A Poetry dependency value is either `"^2.31"` or an inline table `{version = "^2.31", ...}`.
 * A table with no `version` key (`{git = "…"}`, `{path = "…"}`) is a location, not a version line.
 */
function poetrySpec(value: TomlValue): { spec?: string; unresolvedReason?: string } {
  if (value.kind === "string") return { spec: value.value };
  if (value.kind === "table") {
    const versionEntry = value.entries.find(([k]) => k === "version");
    const v = versionEntry?.[1];
    if (v !== undefined && v.kind === "string") return { spec: v.value };
    return {
      unresolvedReason:
        "Poetry table specifier names a location (git/path/url) rather than a registry version line"
    };
  }
  if (value.kind === "array") {
    // Multiple-constraints dependencies: `[{version="^1", python="<3.9"}, …]`. Which one applies
    // depends on the environment, so no single declared version is stateable from the file.
    return {
      unresolvedReason:
        "Poetry multiple-constraints dependency: the applicable version depends on the resolution environment"
    };
  }
  return { unresolvedReason: "unrecognised Poetry dependency value" };
}

function poetryEntries(
  entries: readonly TomlEntry[],
  path: readonly string[],
  scope: DependencyScope,
  out: DeclaredDependency[]
): void {
  for (const entry of tableEntries(entries, path)) {
    // The interpreter constraint, not a package. See the module comment.
    if (entry.key === "python") continue;

    const { spec, unresolvedReason } = poetrySpec(entry.value);
    const declaredIn = path.join(".");

    if (spec === undefined) {
      out.push({
        ecosystem: "python",
        coordinate: entry.key,
        constraint: "unresolved",
        scope,
        declaredIn,
        ...(unresolvedReason !== undefined ? { note: unresolvedReason } : {})
      });
      continue;
    }

    // Poetry's own operators (`^`, `~`, `*`) are ranges; `2.31.0` bare in Poetry means EXACTLY that
    // version (unlike npm's caret default), so it classifies as pinned.
    const constraint: DeclaredDependency["constraint"] =
      spec === "*" ? "unpinned" : /^[0-9]/.test(spec) && !/[,\s*]/.test(spec) ? "pinned" : "range";

    out.push({
      ecosystem: "python",
      coordinate: entry.key,
      ...(constraint === "unpinned" ? {} : { declared: spec }),
      constraint,
      scope,
      ...(() => {
        const v = constraint === "unpinned" ? undefined : comparableFrom(spec);
        return v !== undefined ? { version: v } : {};
      })(),
      declaredIn
    });
  }
}

/**
 * Parse a `pyproject.toml`.
 *
 * @throws {ManifestParseError} when the TOML cannot be read at all — never silently empty, for the
 *   reason given on {@link ManifestParseError}.
 */
export function parsePyprojectToml(content: string): DeclaredDependency[] {
  const entries = scanToml(content);
  const out: DeclaredDependency[] = [];

  // --- PEP 621 -----------------------------------------------------------------------------
  for (const entry of tableEntries(entries, ["project"])) {
    if (entry.key !== "dependencies") continue;
    for (const req of stringItems(entry.value)) {
      const parsed = parsePep508(req);
      if (parsed) out.push(toDeclared(parsed, "runtime", "project.dependencies"));
    }
  }

  for (const entry of tableEntries(entries, ["project", "optional-dependencies"])) {
    for (const req of stringItems(entry.value)) {
      const parsed = parsePep508(req);
      // Optional extras still SHIP — they are runtime code for whoever asks for the extra. The
      // group name is preserved in `declaredIn` so a caller that wants to treat a group named
      // "test" as dev can do so from a DECLARED fact rather than this parser guessing from a name.
      if (parsed)
        out.push(toDeclared(parsed, "runtime", `project.optional-dependencies.${entry.key}`));
    }
  }

  // --- PEP 735 dependency groups (the standard dev-dependency mechanism) --------------------
  for (const entry of tableEntries(entries, ["dependency-groups"])) {
    for (const item of entry.value.kind === "array" ? entry.value.items : []) {
      // `{include-group = "other"}` is a reference to another group, not a package.
      if (item.kind !== "string") continue;
      const parsed = parsePep508(item.value);
      if (parsed) out.push(toDeclared(parsed, "dev", `dependency-groups.${entry.key}`));
    }
  }

  // --- PEP 518 build requirements ----------------------------------------------------------
  for (const entry of tableEntries(entries, ["build-system"])) {
    if (entry.key !== "requires") continue;
    for (const req of stringItems(entry.value)) {
      const parsed = parsePep508(req);
      if (parsed) out.push(toDeclared(parsed, "build", "build-system.requires"));
    }
  }

  // --- Poetry ------------------------------------------------------------------------------
  poetryEntries(entries, ["tool", "poetry", "dependencies"], "runtime", out);
  poetryEntries(entries, ["tool", "poetry", "dev-dependencies"], "dev", out);
  // `[tool.poetry.group.<name>.dependencies]` — the group name is the 4th path segment, so the
  // groups are discovered from the scanned paths rather than from a hard-coded list of names.
  const groupNames = new Set<string>();
  for (const e of entries) {
    if (
      e.path.length === 5 &&
      e.path[0] === "tool" &&
      e.path[1] === "poetry" &&
      e.path[2] === "group" &&
      e.path[4] === "dependencies"
    ) {
      const g = e.path[3];
      if (g !== undefined) groupNames.add(g);
    }
  }
  for (const g of groupNames) {
    poetryEntries(entries, ["tool", "poetry", "group", g, "dependencies"], "dev", out);
  }

  if (out.length === 0 && entries.length === 0) {
    // An entirely empty scan means we were handed something that is not a pyproject.toml at all.
    throw new ManifestParseError("pyproject.toml contained no TOML entries");
  }

  return out;
}
