import type { StackBackend, StackBackendSpec, StackNeed, StackSizeTier } from "@scp/schemas";
import {
  RETARGETABLE_IMAGE_PATHS,
  VALUES_KEY,
  chartBackendDefaults,
  getPath,
  setPath,
  type StackRelease
} from "./release.js";

/**
 * THE ONLY PLACE HELM VALUES ARE MADE (M29.4, ADR-0058). Inputs, and nothing else:
 *   - the backend's spec — an enum, a boolean and an enum (`StackBackendSpecSchema`);
 *   - the release the controller image carries, plus its deploy-time image retargets;
 *   - where SCP lives and its federation role (the controller's own deployment facts);
 *   - secrets the controller itself generated or read back from the backend's namespace.
 * No string from the API reaches this function: `stack-spec-census.test.ts` proves the spec has
 * none to give, and `values.test.ts` proves every value below traces to one of these inputs.
 */

const TIER_FACTOR: Record<StackSizeTier, number> = { small: 1, medium: 2, large: 4 };

/** Multiplies a Kubernetes quantity (`100m`, `128Mi`, `1`, `1Gi`), keeping its unit. */
export function scaleQuantity(q: unknown, factor: number): unknown {
  if (factor === 1) return q;
  const text = typeof q === "number" ? String(q) : q;
  if (typeof text !== "string") return q;
  const m = /^(\d+(?:\.\d+)?)([A-Za-z]*)$/.exec(text.trim());
  if (!m) return q;
  const scaled = Number(m[1]) * factor;
  const rendered = Number.isInteger(scaled) ? String(scaled) : String(Number(scaled.toFixed(3)));
  return `${rendered}${m[2]}`;
}

/** The chart's per-container resources, scaled by the tier. */
export function scaleResources(resources: unknown, tier: StackSizeTier): unknown {
  const factor = TIER_FACTOR[tier];
  if (resources === null || typeof resources !== "object") return resources;
  const out: Record<string, unknown> = {};
  for (const [container, block] of Object.entries(resources as Record<string, unknown>)) {
    const b = (block ?? {}) as Record<string, Record<string, unknown> | undefined>;
    const scaledBlock: Record<string, unknown> = {};
    for (const kind of ["requests", "limits"] as const) {
      const entries = b[kind];
      if (!entries) continue;
      scaledBlock[kind] = Object.fromEntries(
        Object.entries(entries).map(([res, q]) => [res, scaleQuantity(q, factor)])
      );
    }
    out[container] = scaledBlock;
  }
  return out;
}

/** Gitea's generate-once secrets, read back from the live namespace or generated by the controller. */
export interface GiteaSecrets {
  adminPassword: string;
  secretKey: string;
  internalToken: string;
}

export interface ValuesContext {
  release: StackRelease;
  /** The namespace SCP (and this controller) runs in — the bundled NetworkPolicies admit it. */
  scpNamespace: string;
  federationRole: "commander" | "outpost" | "retrans";
  gitea?: GiteaSecrets;
}

export function deriveBackendValues(
  spec: StackBackendSpec,
  ctx: ValuesContext
): Record<string, unknown> {
  const key = VALUES_KEY[spec.backend];
  const defaults = chartBackendDefaults(ctx.release, spec.backend);
  const backendValues: Record<string, unknown> = {
    enabled: true,
    resources: scaleResources(defaults["resources"], spec.sizeTier)
  };
  const values: Record<string, unknown> = {
    federationRole: ctx.federationRole,
    bundledExecutor: { scpNamespace: ctx.scpNamespace, [key]: backendValues }
  };
  for (const [dotted, image] of Object.entries(ctx.release.imageOverrides)) {
    if (!RETARGETABLE_IMAGE_PATHS.includes(dotted)) continue; // parseImageOverrides already refused it
    if (dotted.startsWith(`${key}.`))
      setPath(values["bundledExecutor"] as Record<string, unknown>, dotted, image);
  }
  if (spec.backend === "gitea") {
    if (!ctx.gitea)
      throw new Error("gitea's generate-once secrets must be resolved before rendering it");
    backendValues["adminPassword"] = ctx.gitea.adminPassword;
    backendValues["secretKey"] = ctx.gitea.secretKey;
    backendValues["internalToken"] = ctx.gitea.internalToken;
  }
  return values;
}

/** A value as the chart will see it: the derived override if set, else the chart default. */
function effective(
  values: Record<string, unknown>,
  ctx: ValuesContext,
  backend: StackBackend,
  dotted: string
): unknown {
  const key = VALUES_KEY[backend];
  const derived = getPath(values, `bundledExecutor.${key}.${dotted}`);
  return derived !== undefined
    ? derived
    : getPath(chartBackendDefaults(ctx.release, backend), dotted);
}

/**
 * What an enabled backend still cannot do, from the values it will render with. These are the
 * templates the chart silently omits when a value is missing (proposal §6 "templates that cannot
 * render say so"): the Stack page names them instead.
 */
export function backendNeeds(
  spec: StackBackendSpec,
  values: Record<string, unknown>,
  ctx: ValuesContext
): StackNeed[] {
  if (spec.backend !== "argo-workflows") return [];
  const needs: StackNeed[] = [];
  if (!effective(values, ctx, spec.backend, "catalog.buildRpm.builderImage")) {
    needs.push({
      code: "rpm-builder-image",
      message:
        "RPM builds (scp-build-rpm-v1) are not installed: no builder image is configured for this release."
    });
  }
  if (!effective(values, ctx, spec.backend, "catalog.infra.stateBackend.type")) {
    needs.push({
      code: "infra-state-backend",
      message:
        "Infrastructure plan/apply (scp-infra-plan-v1 / scp-infra-apply-v1) is not installed: no state backend is configured."
    });
  } else if (!effective(values, ctx, spec.backend, "catalog.infra.image")) {
    needs.push({
      code: "infra-runner-image",
      message: "Infrastructure plan/apply needs the scp-runner-iac image, and none is configured."
    });
  }
  return needs;
}
