/**
 * Derives the air-gap variant of `deploy/compose/docker-compose.yml` at BUNDLE BUILD time.
 *
 * The dev/eval compose file (DESIGN.md §16 "Dev / evaluation") builds the `scp` service from
 * source (`build: {context: ../.., dockerfile: Dockerfile}`) — correct for a developer checkout,
 * useless for an air-gapped bundle where there is no source tree, only a pre-built OCI-layout
 * image. This module parses the real compose file with the `yaml` package (already a repo
 * dependency pattern — see `tools/helm-verify`) and replaces `build:` with `image:
 * __SCPD_IMAGE_REF__`, and pins `postgres`'s `image:` to `__POSTGRES_IMAGE_REF__` — both
 * placeholder tokens install.sh substitutes with the real retargeted-registry, digest-pinned
 * refs via a plain `sed`, so install.sh never needs a YAML parser.
 *
 * Deriving this from the real compose file (rather than hand-maintaining a second static
 * template) means the two can't silently drift — any change to service names, env vars, health
 * checks, volumes, or ports in the source file flows through automatically, and this module's
 * own test (`compose-retarget.test.ts`) asserts the specific transform (build->image,
 * postgres->pinned image) rather than the whole file's content, so unrelated source-file edits
 * don't spuriously fail it.
 */
import { parseDocument, isMap } from "yaml";

export const SCPD_IMAGE_PLACEHOLDER = "__SCPD_IMAGE_REF__";
export const POSTGRES_IMAGE_PLACEHOLDER = "__POSTGRES_IMAGE_REF__";

// Deliberately does NOT interpolate SCPD_IMAGE_PLACEHOLDER/POSTGRES_IMAGE_PLACEHOLDER into this
// comment's own text: install.sh's retarget step is a blanket `sed` substitution over the whole
// file (see install.sh's compose-mode block), so a literal occurrence of the placeholder token
// HERE would get rewritten too, garbling the comment with a live digest string spliced into what
// should stay static instructional text — caught by actually running install.sh --mode compose
// end to end and reading the output file, not by inspection alone.
const HEADER_COMMENT = `# GENERATED by @scp/airgap build-bundle from deploy/compose/docker-compose.yml.
# Do not hand-edit — install.sh substitutes the two image-reference placeholder tokens in this
# file with the customer registry's digest-pinned image refs before \`docker compose up\`.
`;

/**
 * Transform the source compose YAML text into the air-gap variant. Throws if the expected
 * `services.scp`/`services.postgres` shape isn't present — a structural change to the source
 * compose file that this function doesn't know how to retarget should fail loudly at bundle-build
 * time, not silently ship a broken compose file into the tarball.
 */
export function buildAirgapCompose(sourceYamlText: string): string {
  const doc = parseDocument(sourceYamlText);
  const services = doc.get("services");
  if (!isMap(services)) {
    throw new Error("compose file has no top-level 'services' map — cannot retarget");
  }

  const scp = services.get("scp");
  if (!isMap(scp)) {
    throw new Error("compose file has no 'services.scp' — cannot retarget the scpd image reference");
  }
  if (!scp.has("build")) {
    throw new Error("services.scp has no 'build' key — expected the dev compose file to build from source (nothing to retarget into an image: ref)");
  }
  scp.delete("build");
  // Put `image:` first for readability — cosmetic only, doesn't affect parsing.
  scp.set("image", SCPD_IMAGE_PLACEHOLDER);

  const postgres = services.get("postgres");
  if (!isMap(postgres)) {
    throw new Error("compose file has no 'services.postgres' — cannot retarget the postgres image reference");
  }
  postgres.set("image", POSTGRES_IMAGE_PLACEHOLDER);

  return HEADER_COMMENT + "\n" + String(doc);
}
