/** Derives the air-gap compose variant at bundle build time. See docs/airgap.md §29. */
import { parseDocument, isMap } from "yaml";

export const SCPD_IMAGE_PLACEHOLDER = "__SCPD_IMAGE_REF__";
export const POSTGRES_IMAGE_PLACEHOLDER = "__POSTGRES_IMAGE_REF__";

// Deliberately does not spell the placeholders in its own text. See docs/airgap.md §30.
const HEADER_COMMENT = `# GENERATED by @scp/airgap build-bundle from deploy/compose/docker-compose.yml.
# Do not hand-edit — install.sh substitutes the two image-reference placeholder tokens in this
# file with the customer registry's digest-pinned image refs before \`docker compose up\`.
`;

/** Transform the source compose YAML text into the air-gap variant. See docs/airgap.md §31. */
export function buildAirgapCompose(sourceYamlText: string): string {
  const doc = parseDocument(sourceYamlText);
  const services = doc.get("services");
  if (!isMap(services)) {
    throw new Error("compose file has no top-level 'services' map — cannot retarget");
  }

  const scp = services.get("scp");
  if (!isMap(scp)) {
    throw new Error(
      "compose file has no 'services.scp' — cannot retarget the scpd image reference"
    );
  }
  if (!scp.has("build")) {
    throw new Error(
      "services.scp has no 'build' key — expected the dev compose file to build from source (nothing to retarget into an image: ref)"
    );
  }
  scp.delete("build");
  // Put `image:` first for readability — cosmetic only, doesn't affect parsing.
  scp.set("image", SCPD_IMAGE_PLACEHOLDER);

  const postgres = services.get("postgres");
  if (!isMap(postgres)) {
    throw new Error(
      "compose file has no 'services.postgres' — cannot retarget the postgres image reference"
    );
  }
  postgres.set("image", POSTGRES_IMAGE_PLACEHOLDER);

  return HEADER_COMMENT + "\n" + String(doc);
}
