/**
 * `manifest.json` (rich, for this package's own Node tooling) and `manifest.sh` (flat
 * `KEY=value` shell-sourceable, for install.sh) — two renderings of the same BundleManifest so
 * install.sh never needs a JSON parser (`jq` is not in this project's documented toolchain,
 * BUILD_AND_TEST.md §1) while verify-bundle.ts/tests get a real structured format.
 *
 * `manifest.sh` variable naming: `<UPPER_SNAKE_NAME>_DIGEST`, `_SOURCE_REF`, `_OCI_TAG` per
 * image, plus `BUNDLE_VERSION`/`BUNDLE_BUILT_AT`, and a `BUNDLE_IMAGE_NAMES` space-separated list
 * so install.sh can loop over images without knowing their names ahead of time.
 */
import type { BundleImage, BundleManifest } from "./types.js";

function shellVarStem(imageName: string): string {
  return imageName.toUpperCase().replace(/[^A-Z0-9]+/g, "_");
}

/** Single-quote a value for safe embedding in a sourced shell script — the only values we ever embed here are digests/refs/timestamps we generated ourselves (never operator input), but this is cheap insurance against a version string containing something shell-special. */
function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

export function renderManifestJson(manifest: BundleManifest): string {
  return JSON.stringify(manifest, null, 2) + "\n";
}

export function parseManifestJson(text: string): BundleManifest {
  const parsed = JSON.parse(text) as BundleManifest;
  if (!parsed.bundleVersion || !Array.isArray(parsed.images)) {
    throw new Error("manifest.json is missing bundleVersion/images — not a valid bundle manifest");
  }
  return parsed;
}

export function renderManifestSh(manifest: BundleManifest): string {
  const lines: string[] = [
    "#!/usr/bin/env bash",
    "# GENERATED by @scp/airgap build-bundle — do not hand-edit. Sourced by install.sh.",
    `BUNDLE_VERSION=${shellQuote(manifest.bundleVersion)}`,
    `BUNDLE_BUILT_AT=${shellQuote(manifest.builtAt)}`,
    `BUNDLE_IMAGE_NAMES=${shellQuote(manifest.images.map((i) => i.name).join(" "))}`,
    ""
  ];
  for (const image of manifest.images) {
    const stem = shellVarStem(image.name);
    lines.push(
      `${stem}_NAME=${shellQuote(image.name)}`,
      `${stem}_SOURCE_REF=${shellQuote(image.sourceRef)}`,
      `${stem}_OCI_TAG=${shellQuote(image.ociTag)}`,
      `${stem}_OCI_PATH=${shellQuote(image.ociPath)}`,
      `${stem}_DIGEST=${shellQuote(image.manifestDigest)}`,
      ""
    );
  }
  return lines.join("\n");
}

export function buildManifest(images: BundleImage[], bundleVersion: string, builtAt: string): BundleManifest {
  return {
    bundleVersion,
    builtAt,
    builtBy: "@scp/airgap build-bundle.ts",
    images
  };
}
