/** Plan a re-vendor of Gitea: render the upstream chart, strip every Secret and the helm-test pod,
 *  extract the four static scripts SCP's own Secrets re-inject, and track the one image. */
import { parseKubernetesImages } from "@scp/dependency-manifests";
import { parse as parseYaml } from "yaml";
import {
  GITEA_BUNDLE_IMAGE_NAME,
  GITEA_CONFIG_SECRET_NAME,
  GITEA_IMAGE_COORDINATE,
  GITEA_INIT_SECRET_NAME,
  GITEA_RELEASE_NAME,
  giteaHelmTemplateArgs
} from "./gitea-backend.js";
import type { BackendName, VendorFile, VendorRefreshIO, VendorRefreshPlan } from "./types.js";

interface RenderedDoc {
  raw: string;
  parsed: Record<string, unknown> | null;
}

/** `helm template` prefixes every document with its own `# Source: <chart>/templates/<file>` comment
 *  line. It carries no information this tool needs (there is exactly one template tree, this chart's
 *  own) and the real vendored file has none — dropped here rather than round-tripped through
 *  `yaml.stringify`, which would also silently reformat every kept document. */
function stripSourceComments(doc: string): string {
  return doc
    .split("\n")
    .filter((line) => !line.startsWith("# Source:"))
    .join("\n")
    .trim();
}

function splitRenderedDocs(raw: string): RenderedDoc[] {
  return raw
    .split(/\n---\n/)
    .map((doc) => stripSourceComments(doc))
    .filter((doc) => doc !== "")
    .map((raw) => ({ raw, parsed: (parseYaml(raw) ?? null) as Record<string, unknown> | null }));
}

function metadataName(doc: Record<string, unknown>): string | undefined {
  const metadata = doc["metadata"];
  if (metadata === null || typeof metadata !== "object") return undefined;
  const name = (metadata as Record<string, unknown>)["name"];
  return typeof name === "string" ? name : undefined;
}

function isHelmTestHookPod(doc: Record<string, unknown>): boolean {
  if (doc["kind"] !== "Pod") return false;
  const metadata = doc["metadata"];
  if (metadata === null || typeof metadata !== "object") return false;
  const annotations = (metadata as Record<string, unknown>)["annotations"];
  if (annotations === null || typeof annotations !== "object") return false;
  const hook = (annotations as Record<string, unknown>)["helm.sh/hook"];
  return typeof hook === "string" && hook.includes("test");
}

/** `stringData` verbatim, or `data` base64-decoded — a real chart may render either. */
function secretPayload(doc: Record<string, unknown>): Record<string, string> {
  const stringData = doc["stringData"];
  if (stringData !== null && typeof stringData === "object") {
    const out: Record<string, string> = {};
    for (const [k, v] of Object.entries(stringData as Record<string, unknown>)) {
      if (typeof v === "string") out[k] = v;
    }
    return out;
  }
  const data = doc["data"];
  if (data !== null && typeof data === "object") {
    const out: Record<string, string> = {};
    for (const [k, v] of Object.entries(data as Record<string, unknown>)) {
      if (typeof v === "string") out[k] = Buffer.from(v, "base64").toString("utf8");
    }
    return out;
  }
  return {};
}

function withTrailingNewline(text: string): string {
  return text.endsWith("\n") ? text : `${text}\n`;
}

function giteaHeader(chartVersion: string, appVersion: string, tag: string): string {
  const flags = [
    `  helm template ${GITEA_RELEASE_NAME} gitea-charts/gitea --version ${chartVersion} --namespace ${GITEA_RELEASE_NAME} \\`,
    `    --set postgresql.enabled=false --set postgresql-ha.enabled=false \\`,
    `    --set valkey-cluster.enabled=false --set valkey.enabled=false \\`,
    `    --set replicaCount=1 --set gitea.config.database.DB_TYPE=sqlite3 \\`,
    `    --set gitea.admin.existingSecret=gitea-admin-secret`
  ].join("\n");
  return [
    "# =============================================================================================",
    "# VENDORED, UNMODIFIED Gitea (Mode B — the default bundled unified registry: image + code +",
    `# package, ADR-0012). Rendered from the upstream Gitea Helm chart gitea-charts/gitea v${chartVersion}`,
    `# (app ${appVersion}, image tag ${tag}) with the SQLite / single-replica / no-external-DB / no-valkey`,
    "# minimal profile:",
    "#",
    flags,
    "#",
    "# Regenerated by tools/vendor-refresh — see that tool's README for what it strips (every Secret,",
    "# the helm-test connection Pod) and where it re-extracts the config/init scripts to",
    "# (vendor/gitea/config/, vendor/gitea/init/). Never hand-edit this file.",
    "# ============================================================================================="
  ].join("\n");
}

export async function planGitea(
  chartRef: string,
  chartVersion: string,
  io: VendorRefreshIO
): Promise<VendorRefreshPlan> {
  const raw = await io.runHelmTemplate(giteaHelmTemplateArgs(chartRef, chartVersion));
  if (raw.trim() === "") {
    throw new Error("vendor-refresh: helm template returned an empty render for gitea");
  }

  const docs = splitRenderedDocs(raw);
  const kept: string[] = [];
  let configScript: string | undefined;
  let initScripts: Record<string, string> | undefined;

  for (const { raw: docRaw, parsed } of docs) {
    if (parsed === null) continue; // a stray `---` with nothing between; not a document
    if (isHelmTestHookPod(parsed)) continue;
    if (parsed["kind"] === "Secret") {
      const name = metadataName(parsed);
      if (name === GITEA_CONFIG_SECRET_NAME) {
        const payload = secretPayload(parsed);
        if (typeof payload["config_environment.sh"] !== "string") {
          throw new Error(
            `vendor-refresh: Secret '${GITEA_CONFIG_SECRET_NAME}' does not carry a ` +
              "'config_environment.sh' key — the chart's config-secret shape changed; update this " +
              "tool's extraction before re-vendoring"
          );
        }
        configScript = payload["config_environment.sh"];
      } else if (name === GITEA_INIT_SECRET_NAME) {
        const payload = secretPayload(parsed);
        const required = [
          "configure_gpg_environment.sh",
          "init_directory_structure.sh",
          "configure_gitea.sh"
        ];
        const missing = required.filter((key) => typeof payload[key] !== "string");
        if (missing.length > 0) {
          throw new Error(
            `vendor-refresh: Secret '${GITEA_INIT_SECRET_NAME}' is missing key(s) ${missing.join(", ")} ` +
              "— the chart's init-secret shape changed; update this tool's extraction before re-vendoring"
          );
        }
        initScripts = {
          "configure_gpg_environment.sh": payload["configure_gpg_environment.sh"]!,
          "init_directory_structure.sh": payload["init_directory_structure.sh"]!,
          "configure_gitea.sh": payload["configure_gitea.sh"]!
        };
      }
      continue; // every Secret is stripped from the vendored manifest, extracted or not
    }
    kept.push(docRaw);
  }

  if (configScript === undefined) {
    throw new Error(
      `vendor-refresh: the render carried no Secret named '${GITEA_CONFIG_SECRET_NAME}' — cannot ` +
        "extract config_environment.sh"
    );
  }
  if (initScripts === undefined) {
    throw new Error(
      `vendor-refresh: the render carried no Secret named '${GITEA_INIT_SECRET_NAME}' — cannot ` +
        "extract the init scripts"
    );
  }

  const declared = parseKubernetesImages(raw).filter(
    (d) => d.constraint !== "unresolved" && d.coordinate === GITEA_IMAGE_COORDINATE
  );
  if (declared.length === 0 || declared[0]!.declared === undefined) {
    throw new Error(
      `vendor-refresh: expected to find '${GITEA_IMAGE_COORDINATE}' in the rendered chart, but it ` +
        "declares no such image — either the upstream layout changed, or this tool's coordinate is stale"
    );
  }
  const tag = declared[0]!.declared!;
  const tagRef = `${GITEA_IMAGE_COORDINATE}:${tag}`;
  const digest = await io.resolveImageDigest(tagRef);

  const appVersionMatch = /-rootless$/.exec(tag);
  const appVersion = appVersionMatch ? tag.slice(0, -appVersionMatch[0]!.length) : tag;

  const files: VendorFile[] = [
    {
      path: "deploy/helm-bundled/vendor/gitea/install-no-secrets.yaml",
      content: withTrailingNewline(
        `${giteaHeader(chartVersion, appVersion, tag)}\n---\n${kept.join("\n---\n")}`
      )
    },
    {
      path: "deploy/helm-bundled/vendor/gitea/config/config_environment.sh",
      content: withTrailingNewline(configScript)
    },
    {
      path: "deploy/helm-bundled/vendor/gitea/init/configure_gpg_environment.sh",
      content: withTrailingNewline(initScripts["configure_gpg_environment.sh"]!)
    },
    {
      path: "deploy/helm-bundled/vendor/gitea/init/init_directory_structure.sh",
      content: withTrailingNewline(initScripts["init_directory_structure.sh"]!)
    },
    {
      path: "deploy/helm-bundled/vendor/gitea/init/configure_gitea.sh",
      content: withTrailingNewline(initScripts["configure_gitea.sh"]!)
    }
  ];

  const backend: BackendName = "gitea";
  return {
    backend,
    tag: chartVersion,
    files,
    trackedImages: [
      { bundleImageName: GITEA_BUNDLE_IMAGE_NAME, tagRef, resolvedRef: `${tagRef}@${digest}` }
    ],
    summary:
      `gitea: vendored gitea-charts/gitea@${chartVersion} (app ${appVersion}) via helm template, ` +
      `stripped ${docs.length - kept.length} document(s) (Secrets + the helm-test pod), extracted 4 ` +
      `static scripts.\n  tracked image ${GITEA_BUNDLE_IMAGE_NAME}: ${tagRef}@${digest}`
  };
}
