/** Gitea is vendored from a Helm chart, not a raw manifest (`ce106b7b`, M15.1c) — rendered in the
 *  SQLite / single-replica / no-external-DB / no-valkey minimal profile, every Secret stripped and
 *  regenerated by SCP itself at install time (`templates/gitea-secrets.yaml`), and the
 *  config/init scripts those Secrets need re-extracted verbatim into their own vendored files. See
 *  `deploy/helm-bundled/vendor/gitea/install-no-secrets.yaml`'s own header for the human-readable
 *  version of this recipe. */

export const GITEA_RELEASE_NAME = "scp-gitea";
export const GITEA_NAMESPACE = "scp-gitea";
/** Real usage only — tests point `runHelmTemplate` at a local fixture chart directory instead. */
export const GITEA_CHART_REPO_URL = "https://dl.gitea.com/charts/";
export const GITEA_CHART_REPO_NAME = "gitea-charts";
export const GITEA_CHART_REF = "gitea-charts/gitea";

/** The exact profile flags the recipe has always used (see the header this tool writes, and
 *  `deploy/helm-bundled/README.md`). Order is cosmetic; the SET is what upstream reads. */
export const GITEA_HELM_VALUE_FLAGS: readonly string[] = [
  "postgresql.enabled=false",
  "postgresql-ha.enabled=false",
  "valkey-cluster.enabled=false",
  "valkey.enabled=false",
  "replicaCount=1",
  "gitea.config.database.DB_TYPE=sqlite3",
  `gitea.admin.existingSecret=gitea-admin-secret`
];

/** The two Secret names the vendored Deployment's own volumes reference (release-independent: they
 *  come from the chart's naming convention applied to {@link GITEA_RELEASE_NAME}, not from anything
 *  this tool invents) — this is the fixed extraction key, matching
 *  `deploy/helm-bundled/templates/gitea-secrets.yaml`'s own comment ("Secret NAMES are the fixed
 *  ones the vendored Deployment references"). */
export const GITEA_CONFIG_SECRET_NAME = GITEA_RELEASE_NAME;
export const GITEA_INIT_SECRET_NAME = `${GITEA_RELEASE_NAME}-init`;

/** The upstream image coordinate SCP tracks (retargets via `bundledExecutor.gitea.image`). */
export const GITEA_IMAGE_COORDINATE = "docker.gitea.com/gitea";
export const GITEA_BUNDLE_IMAGE_NAME = "gitea";

export function giteaHelmTemplateArgs(chartRef: string, chartVersion: string): string[] {
  return [
    "template",
    GITEA_RELEASE_NAME,
    chartRef,
    "--version",
    chartVersion,
    "--namespace",
    GITEA_NAMESPACE,
    ...GITEA_HELM_VALUE_FLAGS.flatMap((flag) => ["--set", flag])
  ];
}
